import Link from "next/link";
import AnimatedLogo from "@/components/ui/AnimatedLogo";
import GameScreenshot from "@/components/ui/GameScreenshot";

const technologies = ["HTML", "CSS", "JavaScript", "Python"];
const screenshots = [{ title: "Mundo HTML", image: "/images/Captura1.png" }, { title: "Mundo CSS", image: "/images/Captura2.png" }, { title: "Mundo JavaScript", image: "/images/Captura3.png" }];

export default function Home() {
  return <main className="min-h-screen overflow-hidden bg-[var(--oc-background)] text-[var(--oc-text)]">
    <section className="relative isolate border-b border-[var(--oc-border)]">
      {/* TODO: Agregar fondo pixel art del mapa principal. */}
      <div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_top_right,var(--oc-teal),transparent_42%),radial-gradient(circle_at_left,var(--oc-primary),transparent_38%)] opacity-35" />
      <nav className="mx-auto flex max-w-7xl items-center justify-between gap-3 px-4 py-5 sm:px-5 md:px-8"><AnimatedLogo className="max-h-8 max-w-28 sm:max-h-10 sm:max-w-40" compact /><div className="flex shrink-0 items-center gap-1 sm:gap-3"><Link className="rounded-xl px-2 py-2 text-xs font-semibold transition hover:bg-[var(--oc-surface)] sm:px-4 sm:text-sm" href="/login">Iniciar sesión</Link><Link className="rounded-xl bg-[var(--oc-primary)] px-3 py-2 text-xs font-semibold text-[#EADCCD] transition hover:bg-[var(--oc-primary-hover)] sm:px-4 sm:text-sm" href="/register">Crear cuenta</Link></div></nav>
      <div className="mx-auto grid max-w-7xl gap-10 px-5 pb-16 pt-12 md:px-8 md:pb-24 md:pt-16 lg:grid-cols-2 lg:items-center lg:py-28"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-[var(--oc-accent)] sm:text-sm sm:tracking-[0.24em]">Aprende jugando</p><h1 className="mt-5 max-w-3xl text-4xl font-black leading-tight tracking-tight sm:text-5xl lg:text-6xl">Tu próxima habilidad empieza con una misión.</h1><p className="mt-6 max-w-xl text-base leading-7 text-[var(--oc-muted)] sm:text-lg sm:leading-8">OVER CODE convierte los desafíos de programación en una aventura: explora, resuelve problemas y desbloquea tu potencial mientras juegas.</p><div className="mt-8 grid gap-3 sm:flex sm:flex-wrap"><Link className="rounded-xl bg-[var(--oc-primary)] px-5 py-3 text-center text-sm font-bold text-[#EADCCD] transition hover:scale-[1.02] hover:bg-[var(--oc-primary-hover)]" href="/login">Iniciar sesión</Link><Link className="rounded-xl border border-[var(--oc-border)] bg-[var(--oc-surface)] px-5 py-3 text-center text-sm font-bold transition hover:bg-[var(--oc-surface-raised)]" href="/register">Crear cuenta</Link><Link className="rounded-xl border border-[var(--oc-accent)]/40 px-5 py-3 text-center text-sm font-bold text-[var(--oc-accent)] transition hover:bg-[var(--oc-accent)]/10" href="/download">Descargar juego</Link></div></div><div className="relative min-h-64 rounded-3xl border border-[var(--oc-border)] bg-[var(--oc-surface)] p-5 shadow-2xl sm:min-h-80 sm:p-8">{/* TODO: Agregar ilustración pixel art del personaje principal. */}<div className="absolute inset-4 rounded-2xl border border-dashed border-[var(--oc-border)] sm:inset-5" /><div className="absolute bottom-5 left-5 right-5 rounded-2xl border border-[var(--oc-border)] bg-[var(--oc-surface-raised)] p-4 sm:bottom-8 sm:left-8 sm:right-8 sm:p-5"><p className="text-xs font-bold uppercase tracking-[0.14em] text-[var(--oc-accent)] sm:tracking-[0.18em]">Misión activa</p><p className="mt-2 text-base font-bold sm:text-lg">Desbloquea tu primer mundo de código.</p><div className="mt-4 h-2 overflow-hidden rounded-full bg-[var(--oc-background)]"><div className="h-full w-2/3 rounded-full bg-[var(--oc-accent)]" /></div></div></div></div>
    </section>
    <section className="mx-auto max-w-7xl px-5 py-20 md:px-8"><div className="max-w-2xl"><p className="text-sm font-bold uppercase tracking-[0.22em] text-[var(--oc-accent)]">La aventura</p><h2 className="mt-3 text-4xl font-black">¿Qué es OVER CODE?</h2><p className="mt-5 leading-8 text-[var(--oc-muted)]">Es una plataforma que acompaña un videojuego educativo de programación. Cada reto está diseñado para ayudarte a pensar como desarrollador mientras progresas dentro de un universo hecho para aprender.</p></div><div className="mt-10 grid gap-5 md:grid-cols-3">{[["Juega", "Convierte la curiosidad en misiones, mundos y progreso visible."], ["Aprende", "Resuelve desafíos para comprender los fundamentos de la programación."], ["Avanza", "Sigue tus logros y presume tu lugar en la comunidad."]].map(([title, description]) => <div className="rounded-2xl border border-[var(--oc-border)] bg-[var(--oc-surface)] p-6" key={title}><h3 className="text-xl font-bold">{title}</h3><p className="mt-3 text-sm leading-6 text-[var(--oc-muted)]">{description}</p></div>)}</div></section>
    <section className="border-y border-[var(--oc-border)] bg-[var(--oc-surface)]"><div className="mx-auto max-w-7xl px-5 py-20 md:px-8"><p className="text-sm font-bold uppercase tracking-[0.22em] text-[var(--oc-accent)]">Tu inventario de habilidades</p><h2 className="mt-3 text-4xl font-black">Tecnologías que aprenderás</h2><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{technologies.map((technology) => <div className="rounded-2xl border border-[var(--oc-border)] bg-[var(--oc-surface-raised)] p-6" key={technology}>{/* TODO: Agregar icono pixel art de la tecnología. */}<p className="text-2xl font-black text-[var(--oc-accent)]">{technology}</p><p className="mt-3 text-sm text-[var(--oc-muted)]">Desbloquea retos y domina sus fundamentos.</p></div>)}</div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-20 md:px-8"><p className="text-sm font-bold uppercase tracking-[0.22em] text-[var(--oc-accent)]">Dentro del juego</p><h2 className="mt-3 text-4xl font-black">Explora los mundos</h2><div className="mt-8 grid gap-5 md:grid-cols-3">{screenshots.map((screenshot) => <GameScreenshot alt={`Captura del ${screenshot.title}`} key={screenshot.title} src={screenshot.image} title={screenshot.title} />)}</div></section>
    <footer className="border-t border-[var(--oc-border)] bg-[var(--oc-surface)]"><div className="mx-auto flex max-w-7xl flex-col gap-4 px-5 py-8 text-sm text-[var(--oc-muted)] md:flex-row md:items-center md:justify-between md:px-8"><AnimatedLogo className="max-h-8 max-w-32" compact /><p>Aprende programación. Juega tu próxima misión.</p><div className="flex gap-4"><Link href="/login">Acceder</Link><Link href="/download">Descargar</Link></div></div></footer>
  </main>;
}
